import type { JourneyScene } from "./types";

export const mockScenes: JourneyScene[] = [
  {
    id: "mock-welcome",
    slug: "welcome",
    type: "welcome",
    title: "Başlamadan önce",
    subtitle: "Bu gece sadece sana ayrıldı.",
    content: "Bu küçük yolculuk, sana söylemek istediğim şeyleri biraz daha özel anlatmak için hazırlandı.",
    dateLabel: "20 Temmuz",
    sortOrder: 1,
    backgroundVariant: "night",
    isLocked: false,
    primaryActionLabel: "İlk sahneye geç",
    isActive: true,
    progressIsCompleted: false,
    progressIsUnlocked: true,
  },
  {
    id: "mock-birthday-note",
    slug: "birthday-note",
    type: "story",
    title: "İyi ki doğdun",
    subtitle: "Bugün senin günün.",
    content: "İyi ki varsın. Hayatıma kattığın sakinliği, neşeyi ve o güzel gülüşünü her gün yeniden seviyorum.",
    sortOrder: 2,
    backgroundVariant: "rose",
    isLocked: false,
    isActive: true,
    progressIsCompleted: false,
    progressIsUnlocked: true,
  },
  {
    id: "mock-anniversary-note",
    slug: "anniversary-note",
    type: "story",
    title: "Bizim günümüz",
    subtitle: "Doğum gününle birlikte, hikayemizin de özel durağı.",
    content: "Bazı tarihler sadece hatırlanmaz, içinden geçtikçe daha kıymetli olur. 20 Temmuz benim için öyle.",
    sortOrder: 3,
    backgroundVariant: "deep",
    isLocked: false,
    isActive: true,
    progressIsCompleted: false,
    progressIsUnlocked: true,
  },
  {
    id: "mock-small-task",
    slug: "small-task",
    type: "task",
    title: "Küçük bir görev",
    subtitle: "Devam etmeden önce bir an dur.",
    content: "Beraber çekildiğimiz en sevdiğin fotoğrafı düşün. O anı aklında tut, finalde lazım olacak.",
    sortOrder: 4,
    backgroundVariant: "champagne",
    isLocked: false,
    isActive: true,
    progressIsCompleted: false,
    progressIsUnlocked: true,
  },
  {
    id: "mock-first-memory",
    slug: "first-memory",
    type: "memory",
    title: "Aklımda kalan an",
    subtitle: "Kalabalık bir galeri değil, tek bir his.",
    content: "Bazı anlar fotoğraftan büyük olur. Seninle sıradan bir gün bile bana iyi gelen bir hatıraya dönüşüyor.",
    dateLabel: "Bizden bir an",
    sortOrder: 5,
    backgroundVariant: "night",
    isLocked: false,
    isActive: true,
    progressIsCompleted: false,
    progressIsUnlocked: true,
  },
  {
    id: "mock-locked-surprise",
    slug: "locked-surprise",
    type: "locked",
    title: "Küçük bir sır",
    subtitle: "Bunu hemen göstermemek istedim.",
    content: "Asıl sürpriz ekranda değil. Birazdan bana bakmanı isteyeceğim.",
    sortOrder: 6,
    backgroundVariant: "rose",
    isLocked: true,
    unlockCondition: "small-task",
    primaryActionLabel: "Sırrı Aç",
    isActive: true,
    progressIsCompleted: false,
    progressIsUnlocked: false,
  },
  {
    id: "mock-final",
    slug: "final",
    type: "final",
    title: "İyi ki sen",
    subtitle: "İyi ki doğdun, iyi ki biz olduk.",
    content: [
      "Bugün sadece doğum günün değil.",
      "Bizim hikayemizin de en güzel duraklarından biri.",
      "Seni seviyorum.",
      "Şimdi asıl sürpriz için bana bak.",
    ].join("\n"),
    sortOrder: 7,
    backgroundVariant: "deep",
    isLocked: false,
    isActive: true,
    progressIsCompleted: false,
    progressIsUnlocked: true,
  },
];
